title: data analyst
author: GitHub User
email: shikeyi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  my first github page
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
